"""
ai_assistant.py
----------------
A simple in-app health assistant chatbot.

By default it runs on lightweight rule-based / keyword matching so the
app works fully offline with zero configuration. If the user supplies
their own Anthropic API key in the sidebar, responses are generated by
Claude instead for richer, more general answers.

IMPORTANT: This assistant is for general informational purposes only
and is NOT a substitute for professional medical advice, diagnosis, or
treatment.
"""

import streamlit as st

DISCLAIMER = (
    "⚠️ This assistant provides general health information only and is "
    "not a substitute for professional medical advice. Always consult a "
    "qualified healthcare provider for diagnosis and treatment."
)

# Simple keyword -> response knowledge base used when no API key is set
KNOWLEDGE_BASE = {
    "diabetes": "Diabetes is a condition where blood glucose levels are too high. "
                "Common symptoms include increased thirst, frequent urination, fatigue, "
                "and blurred vision. Risk factors include obesity, sedentary lifestyle, "
                "and family history. Use the Disease Prediction page to estimate risk.",
    "heart": "Heart disease covers conditions affecting the heart, including coronary "
             "artery disease. Warning signs include chest pain, shortness of breath, "
             "and fatigue during exertion. Key risk factors are high blood pressure, "
             "high cholesterol, smoking, and diabetes.",
    "kidney": "Chronic kidney disease (CKD) involves a gradual loss of kidney function. "
              "Early stages often have no symptoms; later stages may cause swelling, "
              "fatigue, and changes in urination. Diabetes and hypertension are leading causes.",
    "blood pressure": "Normal blood pressure is generally below 120/80 mmHg. Readings "
                       "consistently at or above 130/80 mmHg may indicate hypertension, "
                       "a major risk factor for heart and kidney disease.",
    "bmi": "Body Mass Index (BMI) is calculated as weight(kg) / height(m)^2. "
           "18.5–24.9 is considered a healthy range, 25–29.9 is overweight, and "
           "30+ is considered obese.",
    "diet": "A heart- and kidney-healthy diet generally emphasizes vegetables, fruits, "
            "whole grains, lean protein, and reduced sodium/added sugar intake.",
    "exercise": "Most guidelines recommend at least 150 minutes of moderate aerobic "
                "activity per week to support cardiovascular and metabolic health.",
}


def _rule_based_reply(message: str) -> str:
    message_lower = message.lower()
    matches = [v for k, v in KNOWLEDGE_BASE.items() if k in message_lower]
    if matches:
        return "\n\n".join(matches)
    return (
        "I don't have specific information on that in my offline knowledge base. "
        "Try asking about diabetes, heart disease, kidney disease, blood pressure, "
        "BMI, diet, or exercise — or add an Anthropic API key in the sidebar for "
        "richer, general-purpose answers."
    )


def _claude_reply(message: str, api_key: str, history: list) -> str:
    try:
        import anthropic
    except ImportError:
        return "The 'anthropic' package is not installed. Run: pip install anthropic"

    try:
        client = anthropic.Anthropic(api_key=api_key)
        messages = history + [{"role": "user", "content": message}]
        response = client.messages.create(
            model="claude-sonnet-5",
            max_tokens=600,
            system=(
                "You are a cautious, helpful health information assistant embedded in a "
                "clinical analytics dashboard. Give clear, general educational information. "
                "Always recommend consulting a licensed healthcare professional for personal "
                "medical decisions, diagnosis, or treatment. Do not provide specific dosages "
                "or definitive diagnoses."
            ),
            messages=messages,
        )
        return "".join(block.text for block in response.content if block.type == "text")
    except Exception as e:
        return f"Error contacting Claude API: {e}"


def show_ai_assistant_page():
    st.title("🤖 AI Health Assistant")
    st.caption(DISCLAIMER)

    with st.sidebar:
        st.markdown("#### Assistant Settings")
        api_key = st.text_input("Anthropic API Key (optional)", type="password",
                                 help="Add your own key to enable richer AI-generated answers. "
                                      "Leave blank to use the built-in offline knowledge base.")

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    prompt = st.chat_input("Ask about symptoms, conditions, or general health guidance...")

    if prompt:
        st.session_state.chat_history.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            if api_key:
                reply = _claude_reply(prompt, api_key, st.session_state.chat_history[:-1])
            else:
                reply = _rule_based_reply(prompt)
            st.markdown(reply)

        st.session_state.chat_history.append({"role": "assistant", "content": reply})

    if st.button("🗑️ Clear Conversation"):
        st.session_state.chat_history = []
        st.rerun()
