"""
report_generator.py
--------------------
Generates a downloadable PDF report summarizing a patient's profile
and prediction history, using reportlab. Saved reports are written to
the /reports folder.
"""

import streamlit as st
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from database import get_patients, get_predictions_for_patient

REPORTS_DIR = "reports"


def _build_pdf(patient_row, preds_df, output_path):
    os.makedirs(REPORTS_DIR, exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#2c3e50"))
    elements = []

    elements.append(Paragraph("Smart Healthcare Analytics", title_style))
    elements.append(Paragraph("Patient Health Report", styles["Heading2"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    elements.append(Spacer(1, 20))

    # Patient info table
    patient_data = [
        ["Name", patient_row["name"]],
        ["Age", str(patient_row["age"])],
        ["Gender", patient_row["gender"]],
        ["Phone", patient_row["phone"] or "—"],
        ["Address", patient_row["address"] or "—"],
        ["Patient ID", str(patient_row["id"])],
    ]
    t = Table(patient_data, colWidths=[4*cm, 10*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#ecf0f1")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 24))

    elements.append(Paragraph("Prediction History", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    if preds_df.empty:
        elements.append(Paragraph("No predictions on record.", styles["Normal"]))
    else:
        header = ["Disease", "Result", "Probability", "Risk Level", "Date"]
        rows = [header]
        for _, row in preds_df.iterrows():
            rows.append([
                row["disease"].title(),
                row["result"],
                f"{row['probability']*100:.1f}%",
                row["risk_level"],
                row["created_at"][:16],
            ])
        pred_table = Table(rows, colWidths=[3*cm, 4*cm, 2.5*cm, 2.5*cm, 3*cm])
        pred_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f9fc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(pred_table)

    elements.append(Spacer(1, 30))
    elements.append(Paragraph(
        "Disclaimer: This report is generated by an AI-assisted analytics tool and is intended "
        "to support, not replace, clinical judgment. All findings should be reviewed by a "
        "licensed healthcare professional.",
        styles["Italic"]
    ))

    doc.build(elements)


def show_report_generator_page():
    st.title("📄 Report Generator")

    patients_df = get_patients(st.session_state.username)
    if patients_df.empty:
        st.info("No patients available yet.")
        return

    selected_name = st.selectbox("Select Patient", patients_df["name"].tolist())
    patient_row = patients_df[patients_df["name"] == selected_name].iloc[0]
    preds_df = get_predictions_for_patient(int(patient_row["id"]))

    st.write(f"Prediction records found: **{len(preds_df)}**")
    if not preds_df.empty:
        st.dataframe(preds_df[["disease", "result", "probability", "risk_level", "created_at"]],
                     use_container_width=True)

    if st.button("📑 Generate PDF Report", use_container_width=True):
        filename = f"report_{patient_row['id']}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        output_path = os.path.join(REPORTS_DIR, filename)
        _build_pdf(patient_row, preds_df, output_path)
        st.success("Report generated successfully.")

        with open(output_path, "rb") as f:
            st.download_button(
                label="⬇️ Download PDF Report",
                data=f,
                file_name=filename,
                mime="application/pdf",
                use_container_width=True
            )
